version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.15

executors:
  default:
    docker:
      - image: circleci/node:12

commands:
  npm_install:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
              - node_modules

jobs:
  build:
    executor: default
    working_directory: ~/workdir
    steps:
      - checkout
      - npm_install
      - run: npm run test

  deploy:
    executor: default
    working_directory: ~/workdir
    steps:
      - checkout
      - npm_install
      - run:
          name: build
          command: npm run build
          # command: SAMPLE_ENV=$SAMPLE_ENV npm run build
      - aws-s3/sync:
          from: dist
          to: s3://$AWS_BUCKT_NAME/
          overwrite: true

workflows:
  version: 2
  continuous-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main